### PR TITLE
decode file url with percent escape for android and ios.

### PR DESCRIPTION
**Pull request by JoxC**
Special characters in url are escaped, which would be decoded when converted to path.

### CODE REVIEW

**Comment by shnist** [comment]
hi @JoxC, thank you for your contribution to this project. Would you mind just explaining to me a little more about what issue this PR is trying to resolve? Apologies for my ignorance, I've just started helping to maintain this project and I'm still trying to get my head around everything. All the best

**Comment by uosl** [comment]
@shnist It seems like this fixes https://github.com/pwlin/cordova-plugin-file-opener2/issues/14 for iOS. (I tested the changes in `src/ios/FileOpener2.m` and it fixed issues opening filenames with spaces)

This PR also makes some changes to `FileOpener2.java` but when I applied these changes and tested on Android, I was unable to open any files with the plugin.

So I guess it fixes the issue for iOS but the Android solution isn't working anymore and needs updating.

**Comment by uosl** [comment]
Please ignore what I said about the PR not working for Android; turns out Cordova doesn't take kindly to editing the Java platform source files, but once I applied the changes to a clone of this repo and added the plugin as a local path, the issue was fixed on Android as well.

So this PR fixes https://github.com/pwlin/cordova-plugin-file-opener2/issues/14 for both Android and iOS, according to my testing. Would be great if it could be merged!

**Comment by shnist** [comment]
@uosl thanks for testing this, will merge it in

**Comment by uosl** [comment]
Thanks for the quick merge!

**Pull request merged**
