### PR TITLE
Specify the static version of the Android framework to avoid build error

### PR DESCRIPTION
**Pull request by ivanosire**
Building android platform this error appear:
"ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:fontVariationSettings                                                                                            
ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:ttcIndex"

With the sign + the android framework used is the new and latest version (28.0.0) but seems incompatible now.

I have fixed writing static version of framework 27.1.0

### CODE REVIEW

**Comment by dani-inside** [comment]
Noticed the same issue. Any chance to merge that one please?

**Comment by davidgv88** [comment]
Please Merge!

**Comment by zcoffin86** [comment]
Please merge this!

**Comment by zcoffin86** [comment]
Potentially this implementation would be more agreeable, since it will default to not changing the value yet allows you to explicitly set it in the config. https://github.com/Compeat/cordova-plugin-file-opener2/commit/514dd7d5f60627b9cbe5f01c8beea4a23df1e2b2

**Comment by shnist** [comment]
hi @ivanosire, thank you for your contribution to this project. We have implemented a solution as per https://github.com/Compeat/cordova-plugin-file-opener2/commit/514dd7d5f60627b9cbe5f01c8beea4a23df1e2b2. This is a more flexible solution and is becoming a fairly standardised pattern across the cordova plugin ecosystem. You can now specify the android support version at installation time:
`cordova plugin add cordova-plugin-file-opener2  --variable ANDROID_SUPPORT_VERSION={required version}` . This is available in the new 2.1.0 version. This should help resolve your issue and as such we'll be closing this PR.

**Pull request closed without merging**
