### PR TITLE
Fix opening files when targeting android SDK 28

### PR DESCRIPTION
**Pull request by KleggerKoder**
this fixes issue: https://github.com/pwlin/cordova-plugin-file-opener2/issues/268

### CODE REVIEW

**Comment by WuglyakBolgoink** [comment]
any updates???

**Comment by shnist** [comment]
hi @KleggerKoder, thanks for the pull request! The code you have changed here is 2 years old. If this fixes things when targeting SDK28, is this backwards compatible with older version of the SDK?

**Comment by JamesPeck** [comment]
Any Update?

**Comment by shnist** [comment]
I'm waiting for @KleggerKoder to get back to me.

**Comment by KleggerKoder** [comment]
@shnist Tested and working on targetSdkVersion 28, 26, 24, 23.  
Fails on targetSdkVersion 21 and earlier.

**Comment by nip3o** [comment]
I have this issue and tried installing the plugin from this MR instead of the version in master. I did `cordova platform remove android; cordova platform add android` after changing the plugin and it seems like the MR version is in the `platforms/android/plugins` directory, but I get exactly the same error as before. :/

**Comment by JamesPeck** [comment]
Any updates on this issue?

**Comment by Eugene2799** [comment]
same error. not work for me

**Pull request merged**
