### PR TITLE
Update fileOpener2Proxy.js, Windows fixes.

### PR DESCRIPTION
**Pull request by J3r0M3D3V**
The plugin didn't work on windows, mainly due to uri/path problems (as reported in some issues). I fixed it, + some changes like an error on callback.

### CODE REVIEW

**Comment by hmillet** [comment]
@pwlin @Gillardo @J3r0M3D3V 

Hi,

This pull request was very usefull for us in order to make our app works on Windows.

Could you please check it and if ok for you, accept it ?

Thanks

**Comment by pwlin** [comment]
@Gillardo  Is it ok to merge this?

**Comment by Gillardo** [comment]
Looks fine to me

**Comment by hmillet** [comment]
Hi @pwlin , 

thanks a lot for merging this.

However, when I use the command `cordova plugin add cordova-plugin-file-opener2`, I still get the old code.

I previously clear npm cache using `npm cache clean`

here is my config.xml
`<plugin name="cordova-plugin-file-opener2" spec="~2.0.2" />`

What's wrong with what I do ?

**Comment by J3r0M3D3V** [comment]
Hi,

I'm glad it helped and thanks for the merge :)

**Comment by pwlin** [comment]
@hmillet I upped the version to `2.0.3`. use `spec="~2.0.3"` in your `config.xml`

@J3r0M3D3V  thank you too for sharing your code.

**Comment by hmillet** [comment]
@pwlin it works perfectly. Thanks

**Pull request merged**
