### PR TITLE
Add install option

### PR DESCRIPTION
**Pull request by arj03**

### CODE REVIEW

**Comment by pwlin** [comment]
Hi @arj03 
Thank you for this PR. Can you please elaborate a little bit further? Is there any need for an explicit `install()` function? Isn't simply opening your apk with proper mime type enough to trigger Android's app installer dialog?

**Comment by arj03** [comment]
It might be, but when I looked at your README there was not example of how to install an application from the market, so I had to google how to to it.. I think and explicit install option makes a lot of sense and it makes things a lot more explicit.

**Comment by pwlin** [comment]
OK I understand now. This is "Install From Market" functionality, right? (I see you are firing `market://` protocol).

you can achieve the same results within your own app without needing a plugin. Add a simple `<a href="market://details?id=xxxx" target="_system">Install from Google Play</a>` to your app and then click on the link. It will automatically opens Google Play app. 

The same is valid for iOS platform. Use `<a href="itms-apps://itunes.apple.com/app/my-app/idxxxxxxxx?mt=8" target="_system">Install from App Store</a>` to open App Store app.

Of course you can also use this effect directly with `window.open("[market:// or itms-apps:// link]","_system");`

**Comment by arj03** [comment]
Sure, but it still seems a bit inconsistent to me to have uninstall and not install :)

**Comment by pwlin** [comment]
On the surface it seems inconsistent yes :) But the availability of an `uninstall` function originates from  the fact that there is no way to fire such a command from within your HTML/JS app without resorting to a plugin, while as I mentioned earlier there is a very easy way to fire an `open the market app and go to this app's page` command: by simply using the right protocol (`market://` or `itms-app://`) inside your `<a></a>` tag.

**Comment by arj03** [comment]
Yeah okay, but maybe the README should be updated as least ;)

**Comment by pwlin** [comment]
I will definitely update the README.

**Comment by shnist** [comment]
I have updated the README based on comments from @pwlin and closing the PR.

**Pull request closed without merging**
