### PR TITLE
New Commit 2019 05 12

### PR DESCRIPTION
**Pull request by syaafiqi**
Add new functions:
1. appVersion -- to check installed package version
2. appVersionCode -- to check installed package versionCode

i edit the java files but it's not kinda working.
can you make this official build, i think the concept of function is there. just cant properly build the plugin.

Thanks

### CODE REVIEW

**Comment by shnist** [comment]
@pwlin what's your thoughts on these 2 new methods?

**Comment by pwlin** [comment]
hi @shnist some how I have missed responding to this. I am really sorry. Please do not wait 24 days for a response. Your judgment here is much respected and appreciated!

**Comment by pwlin** [comment]
Hi @syaafiqi thanks for your PR. Your functions are neat and helpful, I think you should create a simple Cordova Plugin out of it. Maybe an utility plugin which returns app's stats/info? :)

**Comment by syaafiqi** [comment]
> Hi @syaafiqi thanks for your PR. Your functions are neat and helpful, I think you should create a simple Cordova Plugin out of it. Maybe an utility plugin which returns app's stats/info? :)

Yeah i think plugin that return app's stats/info could be a thing. Maybe i'll consider to make it. Thank you for ur response and suggestion :)

**Pull request closed without merging**
