### PR TITLE
fix: add Intent.FLAG_ACTIVITY_NEW_TASK flag

### LINKED ISSUE #260: Android 8 open apk file cannot show installed successfully page.
### Expected Behaviour

After using file opener2 to open a apk file to upgrade self, should see apk installed successfully page.

### Actual Behaviour

When I click install button, it crashed.

#### Platform and Version (eg. Android 5.0 or iOS 9.2.1)

Android 8.0+

#### (Android) What device vendor (e.g. Samsung, HTC, Sony...)

Any

#### Cordova CLI info

    cordova info
```
cordova-lib@9.0.1 with:
  cordova-common@3.1.0
  cordova-create@2.0.0
  cordova-fetch@2.0.1
  cordova-serve@3.0.0

Environment:
  OS: win32
  Node: v10.16.0
  npm: 6.9.0

Plugins:
  cordova-plugin-advanced-http
  cordova-plugin-android-permissions
  cordova-plugin-app-version
  cordova-plugin-appavailability
  cordova-plugin-device
  cordova-plugin-file
  cordova-plugin-file-opener2
  cordova-plugin-file-transfer
  cordova-plugin-inappbrowser
  cordova-plugin-ionic-keyboard
  cordova-plugin-ionic-webview
  cordova-plugin-qrscanner
  cordova-plugin-screen-orientation
  cordova-plugin-splashscreen
  cordova-plugin-statusbar
  cordova-plugin-whitelist
  es6-promise-plugin
```

#### Plugin version

    cordova plugin version | grep cordova-plugin-file-opener2

Here is the output:

```
cordova-plugin-file-opener2 2.2.0 "File Opener2"
```

#### Sample Code that illustrates the problem

```ts
    async installApp(apk){
        this.fileOpener.open(apk, 'application/vnd.android.package-archive').then(() => {
        }).catch(async e => {
            this.toast.show('Upgrade failed', 'middle');
        });
    }
```

### PR DESCRIPTION
**Pull request by abcfy2**
Add Intent.FLAG_ACTIVITY_NEW_TASK flag when opening a apk file.

fix #260

### CODE REVIEW

**Comment by abcfy2** [comment]
Hi @shnist . Would you please review my PR? Thanks.

**Comment by shnist** [comment]
Looks good to me.

**Comment by abcfy2** [comment]
Hope a new version would be release soon. :)

**Comment by pwlin** [comment]
Hi @abcfy2 thank you very much, your pull requests are always welcome., And thank you @shnist for taking the time and keeping this plugin alive!

**Pull request merged**
