### PR TITLE
Combined changes to fix FileProvider.java (AndroidX) and remove REQUEST_INSTALL_PACKAGES permission

### LINKED ISSUE #326: android.support.v4.content.FileProvider not found
Was having an issue building for Android on ionic

android.support.v4.content.FileProvider not found

Ionic:

   Ionic CLI                     : 6.18.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.5
   @angular-devkit/build-angular : 0.900.6
   @angular-devkit/schematics    : 9.0.6
   @angular/cli                  : 9.0.6
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : android 10.1.1, ios 6.2.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 19 other plugins)

Utility:

   cordova-res : 0.15.3
   native-run  : 1.5.0

System:

   ios-deploy : 1.11.4
   ios-sim    : 8.0.2
   NodeJS     : v16.10.0 (/usr/local/Cellar/node/16.10.0/bin/node)
   npm        : 7.24.0
   OS         : macOS Big Sur
   Xcode      : Xcode 13.1 Build version 13A1030d

making below change to the FileProvider.java fixes the problem.

Not sure if it is my specific setup or not.

// public class FileProvider extends android.support.v4.content.FileProvider {
// }

public class FileProvider extends androidx.core.content.FileProvider {
}

### PR DESCRIPTION
**Pull request by brospars**
For my own app I had to fix both FileProvider and remove REQUEST_INSTALL_PACKAGES to be compliant with Google new policy.

Fix #326 and #329. Same as #333, #332, #330, #318 and #312 but **combined**.

### CODE REVIEW

**Review by delitamakanda — APPROVED** [review]

**Review by BalaclavaAM — APPROVED** [review]

**Review by miguel-S73 — APPROVED** [review]

**Comment by ShahinBelim** [comment]
Guys, do we expect this PR to be merged? Our app is getting rejected because of this permission issue.

**Comment by brospars** [comment]
I have contacted the owner and other major contributors. Let's hope they let someonelse take over. 🤞

**Comment by shnist** [comment]
@brospars thanks for getting in touch. I can just double check what changes in behaviour users of the plugin can expect when removing `remove REQUEST_INSTALL_PACKAGES`? I'd like to understand if this is a breaking change and if so whether the package needs to be bumped to V4. If you think it would help to update the readme as well please do so.

**Comment by brospars** [comment]
Hi @shnist thanks for the quick response. Yes removing `REQUEST_INSTALL_PACKAGES` can be breaking if you used this plugin to install `.apk`. But this could be easily fixed by adding this permission in your main app `AndroidManifest.xml`. 

Many apps are being rejected because of this, since now you need to justify the usage of this permission. Plus, I don't think plugins should presumed what permission the user will need but instead let the developer set their own permission.

**Comment by shnist** [comment]
hi @brospars - I have created a new release that includes both fixes outlined in this PR (with some extra tidy up work related to the migration of androidX). If you could test it out and feedback I would be grateful.

**Comment by brospars** [comment]
Seems good to me.

**Comment by shnist** [comment]
Great thanks @brospars . I will close this PR.

**Pull request closed without merging**
