### PR TITLE
Fixes https://github.com/pwlin/cordova-plugin-file-opener2/issues/84

### PR DESCRIPTION
**Pull request by lincolnthree**
Fixes https://github.com/pwlin/cordova-plugin-file-opener2/issues/84

Enjoy :)

### CODE REVIEW

**Comment by WuglyakBolgoink** [comment]
HAHA )))))))) I was to late today )))) but thanks anyway!

**Comment by lincolnthree** [comment]
Well, your concepts were a good starting point! I had to do some cleanup and solve a few other issues, but it helped to basically have everything laid out.

**Comment by pwlin** [comment]
Thank you very much for this PR. I really wanted to fix this but had no time chasing after all the recent changes In Android. 

I added both of you to the contributors section, upped the version to `2.0.4`, and pushed the new version to `npm`.

**Comment by lincolnthree** [comment]
Thank you for your quick merge and upload! Fantastic plugin. Keep it up :)

**Comment by WuglyakBolgoink** [comment]
Hi @lincolnthree,


please do quick bug fix ))

you forgot to change "uriString"!!!

```java
    private String stripFileProtocol(String uriString) {
        if (uriString.startsWith("file://")) {
            uriString = uriString.substring(7);
        }

        if (uriString.startsWith("content://")) {
            uriString = uriString.substring(10);
        }

        return uriString;
    }
```

**Comment by pwlin** [comment]
hi @WuglyakBolgoink 

Can you please expand on what you mean? Where is the bug and where you want this code to be added?

**Comment by WuglyakBolgoink** [comment]
Hi @pwlin 

we forgot to write this code in `stripFileProtocol` function:

```
  if (uriString.startsWith("content://")) {
            uriString = uriString.substring(10);
        }
```

**Comment by pwlin** [comment]
Thanks, I fixed the bug and pushed a new version to `npm`. Please upgrade to `2.0.7`

**Comment by lincolnthree** [comment]
Woops! It worked fine for me on a few devices so I didn't think that was necessary. Out of curiosity, what is the scenario in which the plugin fails without stripping the file protocol?

Thanks for catching and updating!

**Comment by WuglyakBolgoink** [comment]
Hallo @lincolnthree ,

without this fix on my `Nexus 5X Android v7.1.x` Plugin doesn't open Files.

**Comment by kirandc** [comment]
Hi @lincolnthree,

Still not opening file on Android v7.0

**Comment by WuglyakBolgoink** [comment]
Hi @kirandc ,

what do you see on LogCat if you try to open file?

**Comment by kirandc** [comment]
@WuglyakBolgoink I am seen this errot "exposed beyond app through Intent.getData()"

**Comment by WuglyakBolgoink** [comment]
@kirandc  Open a new Issue and write full logs

**Pull request merged**
