### PR TITLE
Added support for WP8

### PR DESCRIPTION
**Pull request by Gillardo**
Great plugin.  But i needed support for WP8 as well.  I created it and thought it maybe useful to others too.  So here you are.  I am working on a windows universal app now and will need support for it, so once i have updated that i will send you windows support too.

### CODE REVIEW

**Comment by pwlin** [comment]
Hey @Gillardo this is very nice thank you very much! I merged your pull request. Can you please give me a simple example of how one should use it? for example in Android, you can use this plugin as:

    cordova.plugins.fileOpener2.open(
        '/sdcard/Download/ebook1.pdf', 
        'application/pdf'
    );

How does the path to the pdf file in WP8 look like? What should be used instead of `/sdcard/Download/ebook1.pdf`?

**Comment by Gillardo** [comment]
Hi sorry i havent got ky windows device with me. I will run the code and
tell u output as soon as i can

**Comment by pwlin** [comment]
Hi @Gillardo , Yes it would be great if you provide a little example of how to call this on WP8. I will add it to readme file for other people to use it.

**Comment by Gillardo** [comment]
Np. Also added support for windows too. Will submit pull request within
next few days

**Comment by pwlin** [comment]
Much thanks @Gillardo, looking forward to it!

**Comment by Gillardo** [comment]
@Pwlin So usage for windows phone 8.  At the moment the code only allows access to files and folders within the apps isolated storage.  So for example, you can open a PDF using something like

cordova.plugins.fileOpener2.open(
    'ebook1.pdf', 
    'application/pdf'
);

I believe this is exactly the same, as the current android and ios usage.  I will work on changing the code so you maybe able to access files in other folders, but will submit pull request once i have done that

**Pull request merged**
